"use client";

import { Accordion, AccordionDetails, AccordionSummary, Box, Card, Container, Typography } from "@mui/material";
import { Campaign, Diversity3, ExpandMore, Forum, Gavel, HealthAndSafety, Groups } from "@mui/icons-material";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const activities = [
  { icon: Forum, title: "Social dialogue", text: "Regular consultation with workers, employers, government bodies, and political parties to advance decent work and comprehensive social security." },
  { icon: Campaign, title: "Lobbying & advocacy", text: "Campaigns, rallies, and media engagement that promote fair wages, effective labour legislation, and social-security protections." },
  { icon: HealthAndSafety, title: "Safe workplaces", text: "Occupational health and safety awareness, training, and workplace committees that help create safer conditions for every worker." },
  { icon: Groups, title: "Capacity building", text: "Training, orientations, collective-bargaining support, and leadership development for workers across formal and informal sectors." },
  { icon: Diversity3, title: "Networking", text: "National and international cooperation among unions and solidarity centres to build common strategies for workers’ rights." },
  { icon: Gavel, title: "Mediation & negotiation", text: "Constructive, tripartite dialogue that helps resolve disputes and strengthens a democratic labour market." },
];
const activityDetails = [
  ["Social Dialogue", ["Social dialogue on occupational health and safety is key to institutionalizing labour agendas that lead to the prosperity of both workers and the nation. Existing labour acts and regulations provide some social security for government employees, while many informal-economy workers remain excluded from formal social protection.", "ANTUF regularly consults and holds dialogue with political parties, employers, and government bodies, calling for the ratification and implementation of ILO conventions. It seeks to strengthen right-based dialogue and establish a democratic labour market with social security for wage labourers, self-employed people, poor and marginalized groups."]],
  ["Lobbying and Advocacy", ["Large mass of workers are still subjected to low pay, far below the minimum wage determined by the government. An effective political lobbying in this situation can be one of the most effective strategies to address the workers’ concerns. Considering the need of this hour, ANTUF has been constantly lobbying and advocating for the protection and promotion of their rights. It has been organizing different events like campaigns, rallies, and media programs to press government, employers and political parties to draw their attention to the legislation and implementation of Labor Act and Social Security Bill. ANTUF intends to intensify similar lobbying and advocacy campaigns in collaboration with major national stakeholders in the future as well."]],
  ["Awareness Programs", ["Safe working environment is a basic need for especially informal economy workers. Unfortunately, in Nepal, a large number of workers are unaware about the use of safety measures which sometimes lead to major workplace accidents. Consequently, many workers suffer serious injuries, physical disability and even death due to the lack of required awareness on occupational health. Thus with the purpose of bringing about awareness among the workers on their occupational health and safety, ANTUF organizes awareness campaigns from time to time. In particular, ANTUF has conducted several OSH awareness trainings/orientations to empower the existing OSH committees throughout the nation. It has also been pressing both employers and the government to implement OHS policy to ensure safe working environment in all workplace settings. The initiative taken by ANTUF has brought about many positive changes in workplace environment and saved life of thousands of workers."]],
  ["Capacity Building Training", ["The capacity building training can substantially empower the workers not only to perform their duty swiftly but also to fight for their rights according to changing trends in the labor market. ANTUF has been conducting capacity building programs such as training on the development of LIS, formation of OSH Policy Guidelines, organizing training (OT), on the CBA and the Training of Trainers (ToT) in different corners of the nation, with the participation of a large number of workers from both formal and informal sectors. These programs are facilitated by trade union expert/leaders where participants are encouraged to actively get involved in floor discussion, group work and presentation. Such programs have directly benefitted hundred of trade union leaders/activists across the nation."]],
  ["Networking", ["Networking plays an instrumental role in maintaining uniformity of understanding about the trade union issues and formulating common strategies to get the labor agendas addressed. Effective networking and coordination among the union leaders helps to integrate efforts against unscrupulous employers. ANTUF has developed the culture of networking at national and international levels to foster communication, mutual cooperation and coordination among trade unions and their solidarity centers across the globe. Through regular networking, the unions are brought at the common table to discuss effective strategies to fight the age-old injustice meted out to the workers by their employers. This has helped to some extent in ensuring social security of workers and a democratic labor market in Nepal."]],
  ["Mediation and Negotiation", ["ANTUF has been playing a key role in minimizing antagonism and increasing harmony among the leaders/activists of the trade unions in Nepal. It has made a significant contribution at maintaining an enhanced level of coordination among the unionists and potential stakeholders through its proactive mediation strategy. The idea of single unionism has been pushed ahead simultaneously and unions have become committed towards joint policy issues of the workers. The result is that, a major chunk of central level as well as plant level leaderships have been involved in collaborative efforts to create more coherence in the policies and strategies for the common goal of entire workforce. ANTUF has been playing an important role in facilitating the tri-partite negotiation process for settling the contentious issues in an amicable manner. It has helped the concerned parties/entities to peacefully settle the existing disputes between workers and employers on several occasions."]],
];

export default function AboutUs() {
  return <><Navbar /><Box sx={{ bgcolor: "#f8fafc", color: "#172033" }}>
    <Box sx={{ overflow: "hidden", position: "relative", py: { xs: 8, md: 13 }, background: "linear-gradient(125deg, #0f172a 0%, #164e63 52%, #0f766e 100%)", color: "#fff", "&::after": { content: '""', position: "absolute", width: 520, height: 520, borderRadius: "50%", bgcolor: "rgba(94,234,212,.12)", right: -190, top: -230 } }}><Container maxWidth="lg" sx={{ position: "relative", zIndex: 1 }}><Typography sx={{ color: "#99f6e4", fontWeight: 800, letterSpacing: 2, fontSize: ".78rem", textTransform: "uppercase", mb: 2 }}>About ANTUF</Typography><Typography variant="h1" sx={{ maxWidth: 800, fontWeight: 900, fontSize: { xs: "2.5rem", sm: "3.5rem", md: "4.5rem" }, letterSpacing: "-.045em", lineHeight: 1.06 }}>हाम्रोबारे</Typography><Typography sx={{ mt: 3, maxWidth: 630, color: "rgba(255,255,255,.8)", fontSize: { xs: "1rem", md: "1.15rem" }, lineHeight: 1.75 }}>All Nepal Federation of Trade Unions works to build a fair, safe, and democratic world of work for people across Nepal.</Typography></Container></Box>
    <Container maxWidth="lg" sx={{ py: { xs: 6, md: 10 } }}><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", md: "1.15fr .85fr" }, gap: { xs: 4, md: 7 }, alignItems: "start" }}><Box><Typography sx={{ color: "#0f766e", fontWeight: 800, letterSpacing: 1.3, fontSize: ".78rem", textTransform: "uppercase", mb: 1.5 }}>Who we are</Typography><Typography variant="h2" sx={{ fontWeight: 850, fontSize: { xs: "2rem", md: "2.75rem" }, letterSpacing: "-.035em", lineHeight: 1.15, mb: 2.5 }}>A movement for fair work, social security, and shared prosperity.</Typography><Typography sx={{ color: "#475569", lineHeight: 1.9, fontSize: "1.02rem" }}>Despite the growth of trade unions in Nepal, many workers still face unfair pay, exploitation, discrimination, and unsafe workplaces. ANTUF continuously advocates for their rights through campaigns, capacity building, policy work, and constructive engagement with national stakeholders.</Typography><Typography sx={{ color: "#475569", lineHeight: 1.9, fontSize: "1.02rem", mt: 2 }}>Our work supports workers in both formal and informal economies, with a focus on inclusive social protection, occupational health and safety, democratic labour relations, and strong worker representation.</Typography></Box><Card elevation={0} sx={{ p: { xs: 3, md: 4 }, borderRadius: 4, bgcolor: "#ecfeff", border: "1px solid #a5f3fc" }}><Typography sx={{ color: "#0f766e", fontWeight: 800, mb: 2 }}>Our commitment</Typography><Typography sx={{ color: "#334155", lineHeight: 1.8 }}>We organize, educate, advocate, and negotiate so workers can participate fully in Nepal’s social and economic progress.</Typography><Box sx={{ mt: 3, pt: 2.5, borderTop: "1px solid #a5f3fc", display: "grid", gap: 1.25 }}><Typography fontWeight={750}>• Dignity at work</Typography><Typography fontWeight={750}>• Safe and healthy workplaces</Typography><Typography fontWeight={750}>• Social security for all</Typography><Typography fontWeight={750}>• Democratic labour relations</Typography></Box></Card></Box>
      <Box sx={{ mt: { xs: 7, md: 10 } }}><Typography align="center" sx={{ color: "#0f766e", fontWeight: 800, letterSpacing: 1.3, fontSize: ".78rem", textTransform: "uppercase", mb: 1.5 }}>What we do</Typography><Typography align="center" variant="h2" sx={{ fontWeight: 850, fontSize: { xs: "2rem", md: "2.7rem" }, letterSpacing: "-.035em", mb: 4.5 }}>Advancing workers’ voices, every day.</Typography><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", sm: "repeat(2, 1fr)", md: "repeat(3, 1fr)" }, gap: 2.5 }}>{activities.map(({ icon: Icon, title, text }) => <Card key={title} elevation={0} sx={{ p: 3, borderRadius: 3, border: "1px solid #e2e8f0", height: "100%", transition: "transform .2s, box-shadow .2s", "&:hover": { transform: "translateY(-5px)", boxShadow: "0 15px 30px rgba(15,118,110,.12)" } }}><Box sx={{ display: "grid", placeItems: "center", width: 46, height: 46, borderRadius: 2, bgcolor: "#ccfbf1", color: "#0f766e", mb: 2 }}><Icon /></Box><Typography fontWeight={800} fontSize="1.08rem" mb={1}>{title}</Typography><Typography sx={{ color: "#64748b", fontSize: ".93rem", lineHeight: 1.7 }}>{text}</Typography></Card>)}</Box></Box>
      <Box sx={{ mt: { xs: 7, md: 10 }, maxWidth: 900, mx: "auto" }}><Typography align="center" sx={{ color: "#0f766e", fontWeight: 800, letterSpacing: 1.3, fontSize: ".78rem", textTransform: "uppercase", mb: 1.5 }}>Activities & campaigns</Typography><Typography align="center" variant="h2" sx={{ fontWeight: 850, fontSize: { xs: "2rem", md: "2.7rem" }, letterSpacing: "-.035em", mb: 2 }}>Our work in detail.</Typography><Typography align="center" sx={{ color: "#64748b", lineHeight: 1.75, mb: 4 }}>ANTUF conducts multi-dimensional programmes to safeguard workers’ rights, including joint OSH committees, policy work on social security, and initiatives for decent work.</Typography><Box>{activityDetails.map(([title, paragraphs]: any) => <Accordion key={title} disableGutters elevation={0} sx={{ mb: 1.25, border: "1px solid #e2e8f0", borderRadius: "12px !important", overflow: "hidden", "&:before": { display: "none" } }}><AccordionSummary expandIcon={<ExpandMore />} sx={{ px: { xs: 2, sm: 3 }, "& .MuiAccordionSummary-content": { my: 2 } }}><Typography fontWeight={800}>{title}</Typography></AccordionSummary><AccordionDetails sx={{ px: { xs: 2, sm: 3 }, pt: 0, pb: 3 }}>{paragraphs.map((paragraph: string) => <Typography key={paragraph.slice(0, 32)} sx={{ color: "#475569", lineHeight: 1.85, mb: 1.5 }}>{paragraph}</Typography>)}</AccordionDetails></Accordion>)}</Box></Box>
    </Container>
  </Box><Footer /></>;
}
